### ISSUE TITLE
demo examples don't work

### ISSUE THREAD

**Issue by minskmaz** [ncolony/ncolony#91]
(venv) => twistd -n ncolony --messages messages --config conf
2018-09-30T09:38:09-0700 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 18.7.0 (/Users/nona/projects/ncolony_test/venv/bin/python 2.7.10) starting up.
2018-09-30T09:38:09-0700 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.

Good so far... but then (and right from the example here https://ncolony.readthedocs.io/en/latest/running.html#running-ncolony):

(venv) => python -m ncolony ctl add my-cat-program --cmd cat
usage: __main__.py [-h] --messages MESSAGES --config CONFIG
                   {restart-all,restart,remove,add} ...
__main__.py: error: argument --messages is required

Fiddling with arguments specified in the trace doesn't seem to work.

Suggestions welcomed.

**Comment by moshez** [comment]
Please review the PR -- #92

**Comment by apnewberry** [comment]
The updated version doesn't quite work for me:

```bash
mkdir messages conf
twistd -n ncolony --messages "$PWD"/messages --config "$PWD"/conf
```

In another tab:

```bash
$ python -m ncolony ctl --messages "$PWD"/messages --config "$PWD"/conf add  my-cat-program --cmd cat
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/ncolony/__main__.py", line 21, in <module>
    output=sys.stdout
  File "/home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/gather/api.py", line 200, in run
    commands[argv[0]](argv)
  File "/home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/ncolony/ctllib.py", line 212, in main
    call(ns)
  File "/home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/ncolony/ctllib.py", line 175, in call
    func(places, **results)
  File "/home/user/.envs/dotfiles-_bp8OBTv/lib/python3.6/site-packages/ncolony/ctllib.py", line 72, in add
    args = [cmd]+args
TypeError: can only concatenate list (not "NoneType") to list

```

but `echo` works:
```bash
python -m ncolony ctl --messages "$PWD"/messages --config "$PWD"/conf add  my-echo-program --cmd echo --arg hi
```
twistd's tab shows:
```
2018-11-29T04:08:24+0000 [-] [my-echo-program] hi 
```

Ubuntu 18.04 
Python 3.6.6
twistd 18.7.0
ncolony 18.6.0
